disabled_rules: # rule identifiers to exclude from running
 - conditional_returns_on_newline
 - opening_brace
 - private_outlet
 - switch_case_on_newline
 - trailing_whitespace
 - vertical_whitespace
 - redundant_optional_initialization
 - sorted_imports
 - missing_docs #for now because this can't work with Xcode 8 doc strings.
 - shorthand_operator

opt_in_rules:
 - closure_spacing
 - empty_count
 - explicit_init
 - force_unwrapping
 - overridden_super_call
 - redundant_nil_coalescing
 - attributes
 - closure_end_indentation
 - first_where
 - operator_whitespace
 - operator_usage_whitespace

excluded:
 - Pods
 - Tests

attributes:
  severity: error

class_delegate_protocol: error
compiler_protocol_init: error
closure_end_indentation: error
closure_parameter_position: error
closing_brace: error
closure_spacing: error
colon:
  severity: error

comma: error
conditional_returns_on_newline: error
control_statement: error
empty_count: error
empty_parameters: error
empty_parentheses_with_trailing_closure: error
explicit_init: error
first_where: error
force_cast: error
force_try: error
force_unwrapping: error
implicit_getter: error
large_tuple:
    warning: 3
    error: 3

leading_whitespace: error
legacy_cggeometry_functions: error
legacy_constant: error
legacy_constructor: error
legacy_nsgeometry_functions: error
    
mark: error
nesting: error
operator_whitespace: error
operator_usage_whitespace: error
overridden_super_call:
  severity: error

redundant_nil_coalescing:
  severity: error

redundant_void_return: error
return_arrow_whitespace: error
redundant_string_enum_value: error
statement_position:
  severity: error

todo: error
trailing_newline: error
trailing_semicolon: error
trailing_comma:
  severity: error

unused_closure_parameter: error
unused_enumerated: error
unused_optional_binding: error
valid_docs: error
valid_ibinspectable: error
void_return: error
vertical_parameter_alignment: error
weak_delegate: error

cyclomatic_complexity:
  warning: 15
  error: 15

file_length:
  warning: 1000
  error: 1000

function_body_length:
  warning: 50
  error: 50

function_parameter_count:
  warning: 6
  error: 6

line_length:
  warning: 150
  error: 150

type_body_length:
  warning: 1000
  error: 1000

type_name:
  min_length:
    warning: 1
    error: 1
  max_length:
    warning: 50
    error: 50

variable_name:
  min_length:
    warning: 0
    error: 0

  max_length:
    warning: 50
    error: 50

custom_rules:
  open_bracket_on_new_line:
    included: ".*.swift"
    name: "Opening bracket on new line."
    regex: "((func|var|class|struct|enum|if|switch|guard|protocol|extension|else)[^\n]*\\{$)"
    message: "Opening bracket MUST be on new line."
    severity: error
  
