use_frameworks!

def shmavplayerinterface_dev
    pod 'SHMAVPlayerInterface', :path => '../'
end


def default_pods
    shmavplayerinterface_dev
end

def test_frameworks
    shmavplayerinterface_dev

    pod 'Nimble'
    pod 'RxBlocking'
    pod 'RxTest'
    pod 'GCDWebServer'
end

#IOS
target :SHMAVPlayerIntefaceExampleiOS do
    platform :ios, '9.3'

    default_pods
end

target :SHMAVPlayerIntefaceExampleIOSTests do
    platform :ios, '9.3'

    default_pods
    test_frameworks
end

#TVOS
target :SHMAVPlayerInterfaceExampleTVOS do
    platform :tvos, '10.0'

    default_pods
end

target :SHMAVPlayerInterfaceExampleTVOSTests do
    platform :tvos, '10.0'

    default_pods
    test_frameworks
end

